Feature/storage service
lunasoft/sdk-java18 pull request #28
Opened 2022-11-10 20:47 UTC by marifersw

2022-11-10 22:30 UTC, SwAeyrton requested changes

2022-11-10 22:30 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/storage/Storage.java
> +        StorageResponse response = handler.getHTTP(getUrlapi().isEmpty() ? getUrl() : getUrlapi(),
Como getUrlapi() puede devolver null, al evaluear si esta vacio se lanza un exception, seria modificar la condicional evaluando si es null

2022-11-10 22:30 UTC, SwAeyrton commented on src/test/java/mx/com/sw/services/storage/StorageTest.java
> +package mx.com.sw.services.storage;
Fallan las UT por lo mismo que te comento, se lanza un null exception.

2022-11-16 18:51 UTC, SwAeyrton approved these changes

2022-11-16 18:52 UTC, FerCarrilloM approved these changes

2022-11-16 18:52 UTC, martinfnsw approved these changes

2022-11-16 18:52 UTC, ReyesSW approved these changes

2022-11-16 18:53 UTC, merged