Feacture/ss 169
lunasoft/sdk-java18 pull request #34
Opened 2022-12-14 17:42 UTC by FerCarrilloM

2022-12-14 18:04 UTC, ReyesSW approved these changes
Me agrada, si se ve visualmente directamente en el file readme se mira bien.

2022-12-15 21:47 UTC, ReyesSW approved these changes

2022-12-16 15:20 UTC, SwAeyrton requested changes
Nuevamente el nombre de la rama esta mal.
Falta aumentar la version.

2022-12-16 19:24 UTC, martinfnsw approved these changes

2022-12-16 19:32 UTC, marifersw approved these changes

2022-12-16 20:21 UTC, SwAeyrton approved these changes

2022-12-16 20:22 UTC, merged