Feature/regenerate pdf
lunasoft/sdk-java18 pull request #36
Opened 2022-12-26 19:43 UTC by FerCarrilloM

2022-12-27 15:43 UTC, SwAeyrton requested changes
Fallaron los pipelines, algunas UT tienen error,
![image](https://user-images.githubusercontent.com/88451104/209689248-ae7dcfd6-7538-4bcf-b1b4-ba09ebe81c06.png)

2022-12-28 19:08 UTC, martinfnsw commented on src/main/java/mx/com/sw/services/pdf/Pdf.java
> +        } catch (Exception e) {
Existe ServiceException, estaría bien seguir esta estructura

2022-12-30 16:26 UTC, martinfnsw approved these changes

2022-12-30 16:29 UTC, SwAeyrton approved these changes

2022-12-30 16:32 UTC, marifersw approved these changes

2022-12-30 16:38 UTC, merged