Feature/gobjal 4
lunasoft/sdk-java18 pull request #4
Opened 2020-12-15 23:54 UTC by jmanuelcc

Se agrego cliente para consumir servicio generador de PDFs

2020-12-16 00:10 UTC, JuanGamezSW commented
Recomendaría hacer el "mvn package" para ver los errores de estilos que se obtienen. Algunos son por el orden del import que no se cumple, otros por espacios en blanco, y demás faltas según las buenas prácticas para documentación y código de Java.

```
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[1] (misc) NewlineAtEndOfFile: El fichero no termina con un retorno de carro.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[5] (imports) ImportOrder: Separación extra en el grupo de importación antes 'org.apache.http.client.config.RequestConfig'
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[7] (imports) ImportOrder: Orden incorrecto para el import 'mx.com.sw.exceptions.ServicesException'.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[7] (imports) ImportOrder: Separación extra en el grupo de importación antes 'mx.com.sw.exceptions.ServicesException'
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[14] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[15] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[37,5] (whitespace) EmptyLineSeparator: '/*' cuenta con más de 1 líneas vacías antes.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[62] (javadoc) JavadocStyle: La primera frase debería finalizar con un punto.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[74] (javadoc) JavadocStyle: La primera frase debería finalizar con un punto.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[86] (javadoc) JavadocStyle: La primera frase debería finalizar con un punto.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[98] (javadoc) JavadocStyle: La primera frase debería finalizar con un punto.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[110] (sizes) LineLength: La línea es mayor de 120 caracteres (encontrado 127).
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[115,53] (whitespace) WhitespaceAround: '||' no está precedido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[115,78] (whitespace) WhitespaceAround: '?' no está precedido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[115,78] (whitespace) WhitespaceAround: '?' no está seguido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[115,87] (whitespace) WhitespaceAround: ':' no está precedido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[115,87] (whitespace) WhitespaceAround: ':' no está seguido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\Pdf.java:[116] (sizes) LineLength: La línea es mayor de 120 caracteres (encontrado 124).
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[1] (misc) NewlineAtEndOfFile: El fichero no termina con un retorno de carro.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[6] (imports) ImportOrder: Orden incorrecto para el import 'com.google.gson.Gson'.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[6] (imports) ImportOrder: Separación extra en el grupo de importación antes 'com.google.gson.Gson'
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[9] (imports) ImportOrder: Separación extra en el grupo de importación antes 'mx.com.sw.services.Services'
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[16] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[17] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[22] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[33] (indentation) Indentation: ctor def el descendiente en el nivel de sangrado 6 no está al nivel correcto, 8
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[79] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[82] (indentation) Indentation: method def el descendiente en el nivel de sangrado 10 no está al nivel correcto, 8
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[83] (blocks) NeedBraces: La construcción 'if' debe usar '{}' (llaves).
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[83] (indentation) Indentation: if en el nivel de sangrado 10 no está al nivel correcto, 8
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[83,11] (whitespace) WhitespaceAround: 'if' no está seguido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[83,18] (whitespace) WhitespaceAround: '!=' no está precedido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[83,18] (whitespace) WhitespaceAround: '!=' no está seguido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[85] (blocks) NeedBraces: La construcción 'if' debe usar '{}' (llaves).
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[85] (indentation) Indentation: if en el nivel de sangrado 10 no está al nivel correcto, 8
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[85,11] (whitespace) WhitespaceAround: 'if' no está seguido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[85,20] (whitespace) WhitespaceAround: '!=' no está precedido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[85,20] (whitespace) WhitespaceAround: '!=' no está seguido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[85,43] (whitespace) WhitespaceAround: '>' no está precedido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[85,43] (whitespace) WhitespaceAround: '>' no está seguido de espacio en blanco.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[88] (indentation) Indentation: method def el descendiente en el nivel de sangrado 10 no está al nivel correcto, 8
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[89] (indentation) Indentation: method def el descendiente en el nivel de sangrado 10 no está al nivel correcto, 8
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[92] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[93] (whitespace) EmptyLineSeparator: 'METHOD_DEF' cuenta con más de 1 líneas vacías antes.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[99] (whitespace) EmptyLineSeparator: 'METHOD_DEF' cuenta con más de 1 líneas vacías después.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfService.java:[100] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[2] (whitespace) EmptyLineSeparator: 'import' debe ser separado de la declaración anterior.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[4] (imports) ImportOrder: Orden incorrecto para el import 'mx.com.sw.exceptions.ServicesException'.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[4] (imports) ImportOrder: Separación extra en el grupo de importación antes 'mx.com.sw.exceptions.ServicesException'
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[10] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[11] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[28] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[60,5] (whitespace) EmptyLineSeparator: '/*' cuenta con más de 1 líneas vacías antes.
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidation.java:[69] (blocks) NeedBraces: La construcción 'if' debe usar '{}' (llaves).
[ERROR] src\main\java\mx\com\sw\services\pdf\PdfValidat [...]

2020-12-16 18:00 UTC, JuanGamezSW requested changes
Dejo unos comentarios fáciles.

2020-12-16 18:00 UTC, JuanGamezSW commented on src/test/java/mx/com/sw/services/pdf/PdfTest.java
> +
Tambien faltan UT de errores, url null, usuario incorrecto.

2020-12-17 23:29 UTC, JuanGamezSW approved these changes

2020-12-23 17:18 UTC, helttonrl approved these changes

2021-01-04 17:27 UTC, hermesjimenez approved these changes

2021-01-04 22:06 UTC, closed without merging