Feature/api csd
lunasoft/sdk-java18 pull request #41
Opened 2023-05-18 19:29 UTC by FerCarrilloM

2023-05-19 15:26 UTC, SebastianSW approved these changes

2023-05-23 22:40 UTC, martinfnsw approved these changes

2023-05-24 17:57 UTC, SwAeyrton requested changes

2023-05-24 17:57 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/csd/CsdUtils.java
> +    public CsdUtils(String url, String user, String password, String proxy,
En javadoc se espcifica que se reciben dos parametros url  y urlapi pero en el constructor solo se recibe una url

2023-05-24 17:57 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/csd/CsdUtils.java
> +     * @param url       url base de la API
Evitar mencionar Url de la API si la url que se espera es la de services.

2023-05-24 17:57 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/csd/CsdUtils.java
> +     * @param url       url base de la API
Url API en lugar de Url Services.

2023-05-24 17:57 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/csd/responses/CsdData.java
> +    public String getCertificate_number() {
Mantener una sola forma de nombrar los metodos publicos, en efecto al response que devuelve el servicio es snake case pero segun veo se ha estado usando camelCase

2023-05-24 19:26 UTC, FerCarrilloM commented on src/main/java/mx/com/sw/services/csd/CsdUtils.java
> +     * @param url       url base de la API
Se corrige a url Services

2023-05-24 19:26 UTC, FerCarrilloM commented on src/main/java/mx/com/sw/services/csd/CsdUtils.java
> +     * @param url       url base de la API
Se corrige a url Services

2023-05-24 19:26 UTC, FerCarrilloM commented on src/main/java/mx/com/sw/services/csd/responses/CsdData.java
> +    public String getCertificate_number() {
Se modifican el nombre de los métodos a camelCase en este archivo y en el Request.

2023-06-01 22:19 UTC, SwAeyrton approved these changes

2023-06-01 22:21 UTC, merged