Feature/status-cfdi
lunasoft/sdk-java18 pull request #42
Opened 2023-06-02 00:42 UTC by SebastianSW

2023-06-02 17:52 UTC, FerCarrilloM approved these changes

2023-06-06 15:47 UTC, ReyesSW approved these changes

2023-06-06 16:23 UTC, martinfnsw requested changes
-Falta agregar java docs
-Se recomienda seguir la estructura de las carpetas, clases response en carpeta response y clases request en carpeta request.
¿algún motivo para nombrar clases como StatusCancelation?

2023-06-07 17:48 UTC, SwAeyrton requested changes

2023-06-07 17:48 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/StatusCfdi/StatusCfdiService.java
> +        this.Action = Action;
Este parametro para que es? Si es para el SOAPAction, no es correcto que se le solicite al usuario, debe estar configurado por no decir quemado en codigo ya que independientemente del environment, sigue siendo el mismo valor.

2023-06-08 22:44 UTC, SwAeyrton requested changes

2023-06-08 22:44 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/StatusCfdi/StatusCfdi.java
> +    public StatusCfdi() {
Aqui deberia solicitar la url, ya que el usuario debe poder especificar si es en pruebas o prod

2023-06-08 22:44 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/StatusCfdi/StatusCfdiService.java
> +    private String URL = "https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc";
no quemar el valor, el usuario lo debe pasar en el constructor

2023-06-08 22:44 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/StatusCfdi/StatusCfdi.java
> +
falta javadoc

2023-06-08 22:44 UTC, SwAeyrton commented on src/test/java/mx/com/sw/services/StatusCfdi/StatusCfdiServiceTest.java
> +}
faltan UT probando el servicio en test asi como y escenarios de error.

2023-06-13 22:32 UTC, SwAeyrton approved these changes

2023-06-13 22:38 UTC, marifersw approved these changes

2023-06-13 23:43 UTC, martinfnsw approved these changes

2023-06-13 23:53 UTC, merged