Feature/ss251account balance
lunasoft/sdk-java18 pull request #47
Opened 2023-11-22 07:59 UTC by marifersw

2023-11-22 17:10 UTC, SebastianSW approved these changes

2023-11-23 23:50 UTC, ReyesSW approved these changes

2023-11-24 23:11 UTC, SwAeyrton requested changes

2023-11-24 23:11 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/balance/AccountBalance.java
> +     * @param url       URL base de la API.
la descripcion de este param es incorrecto

2023-11-24 23:11 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/balance/AccountBalance.java
> +    public AccountActionsData addStamps(UUID idUser, int stamps, String comment) throws ServicesException {
Sugiero seguir el mismo nombrado que otras clases Response, tipo AccountActionResponse

2023-11-26 19:50 UTC, martinfnsw commented on src/main/java/mx/com/sw/services/account/balance/AccountBalance.java
> +        return handler.getHTTP(getUrl(), SERVICE_BALANCE_PATH, headers, config, AccountBalanceResponse.class);
Aquí también puedes usar un operador ternario para condicionar las url y utilizar un solo path "management/api/balance/"

2023-11-29 18:58 UTC, martinfnsw approved these changes

2023-12-01 05:19 UTC, SwAeyrton approved these changes

2023-12-01 05:20 UTC, merged