Feature/ss255 account user
lunasoft/sdk-java18 pull request #48
Opened 2023-12-05 22:14 UTC by ReyesSW

Se agregan los metodos para la api de usuario.

2023-12-05 22:32 UTC, SwAeyrton requested changes
Falta actualizar la version

2023-12-05 22:32 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
>       * @param url       url base de la API
no coincide el nombre del param

2023-12-05 22:32 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountListDataResponse getInfoAllUsers(int page, int pageSize) throws ServicesException {
todos estos metodos no tienen relacion con el getInfo, puede quedar como getAllUsers, getUser, createUser, deleteUser

2023-12-05 22:32 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/info/AccountInfoService.java
> +
cuidar los espacios de mas

2023-12-06 00:25 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
>       * @param url       url base de la API
Correcto, es urlApi, se corrije

2023-12-06 00:25 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfoService.java
> +
Se eliminan espacios de archivos que tienen ese espacio extra

2023-12-06 00:25 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountListDataResponse getInfoAllUsers(int page, int pageSize) throws ServicesException {
Se elimina el "Info" y se dejan getAllUsers, getUser, createUser, deleteUser

2023-12-06 00:26 UTC, ReyesSW commented
Se verifican los params de los demas metodos, que todos coincidan.
Se eliminan espacios de archivos

2023-12-06 00:28 UTC, SebastianSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
>       * @param url       url base de la API
Creo falta agregar al javadoc el parámetro de urlApi

2023-12-06 00:31 UTC, SebastianSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountInfoResponse getInfoById(String IdUser) throws ServicesException {
Si es camelCase debería ser idUser

2023-12-06 00:46 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountInfoResponse getInfoById(String IdUser) throws ServicesException {
Gracias, se modifica la variable

2023-12-06 00:46 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
>       * @param url       url base de la API
Es correcto, falto

2023-12-06 15:22 UTC, ReyesSW commented on README.md
> +            AccountInfo account = new AccountInfo("http://services.test.sw.com.mx", settings.getTokenSW(), null, 0);
Se corrijen, efectivamente debe ser api.test :D

2023-12-06 17:21 UTC, FerCarrilloM approved these changes

2023-12-06 18:49 UTC, martinfnsw commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountInfoActionResponse createUser(String email, String password, String name, String rfc, int profile,
Si esta función es de uso interno debería estar como privada para que no existan 2 métodos públicos (getcreateuser y createuser)

2023-12-06 18:49 UTC, martinfnsw commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountInfoActionResponse getCreateUser(String email, String password, String name, String rfc, int profile,
estaría bien agregar javadoc para darle una descripción al cliente de las propiedades.

2023-12-06 19:01 UTC, martinfnsw approved these changes

2023-12-06 19:02 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    //Metodos de respuesta con array de todos los datos de usuarios
Javadoc  format no correcto

2023-12-06 19:03 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountInfoActionResponse createUser(String email, String password, String name, String rfc, int profile,
por que hay dos metodos createuser? cual es el bueno que deberia ser publico?

2023-12-06 19:04 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/info/AccountInfoService.java
> +    public abstract AccountInfoActionResponse getCreateUser(String email, String password, String name, String rfc, int profile, int stamps, boolean unlimited, boolean active) throws ServicesExceptio
es un get o un create?

2023-12-06 19:04 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/account/info/AccountInfoService.java
> +    public abstract AccountInfoActionResponse getDeleteIdUser(String idUser) throws ServicesException;
es un get o un delete?

2023-12-07 04:02 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountInfoActionResponse createUser(String email, String password, String name, String rfc, int profile,
Es correcto, esta es interna. Se coloca como Private.

2023-12-07 04:03 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfo.java
> +    public AccountInfoActionResponse createUser(String email, String password, String name, String rfc, int profile,
Es correcto, esta es la privada, gestiona el armado del Map<>

2023-12-07 04:55 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfoService.java
> +    public abstract AccountInfoActionResponse getCreateUser(String email, String password, String name, String rfc, int profile, int stamps, boolean unlimited, boolean active) throws ServicesExceptio
Se cambia a Create

2023-12-07 04:55 UTC, ReyesSW commented on src/main/java/mx/com/sw/services/account/info/AccountInfoService.java
> +    public abstract AccountInfoActionResponse getDeleteIdUser(String idUser) throws ServicesException;
Se cambia a Delete

2023-12-07 06:00 UTC, ReyesSW commented
Se generan pruebas para que en todo momento pasen sin importar datos de usuario,
Se ajustan nombres.
Queda una func como private.
Se agrega Javadoc a funciones.

2023-12-07 17:02 UTC, SwAeyrton approved these changes

2023-12-07 17:04 UTC, marifersw approved these changes

2023-12-07 18:00 UTC, merged