Feature/ss246
lunasoft/sdk-java18 pull request #51
Opened 2024-01-08 16:05 UTC by FerCarrilloM

Se agregan él envió de parámetros CustomId y extra (Confirmación de generación de PDF) en servicio IssueV4/IssueJSONV4/StampV4

2024-01-08 18:22 UTC, SwAeyrton requested changes

2024-01-08 18:22 UTC, SwAeyrton commented on src/main/java/mx/com/sw/services/issue/BaseStampIssueJsonV4.java
> +    protected Map<String, String> getHeaders(String emails, String customId, boolean extra) throws ServicesException {
a mi parecer el uso de la palabra extra no representa lo que realiza ese bool a menos que se visualice el javadoc

2024-01-08 18:22 UTC, SwAeyrton commented on src/main/java/mx/com/sw/helpers/GeneralValidations.java
> +    protected boolean validateEmails(String emails) throws ServicesException {
Lo mejor es recibir un array de strings, validar sobre cada uno de ellos, esta forma de validar esta muy compleja para lo que es

2024-01-08 18:33 UTC, ReyesSW approved these changes

2024-01-08 18:53 UTC, FerCarrilloM commented on src/main/java/mx/com/sw/helpers/GeneralValidations.java
> +    protected boolean validateEmails(String emails) throws ServicesException {
Gracias.
El servicio ya hacia él envió de un email como String y para no cambiar mucho la estructura anterior busque conservarla.
Realizo el cambio.

2024-01-08 20:24 UTC, FerCarrilloM commented on src/main/java/mx/com/sw/helpers/GeneralValidations.java
> +    protected boolean validateEmails(String emails) throws ServicesException {
Se modifica validación y se aceptan un array de Strings

2024-01-08 20:25 UTC, FerCarrilloM commented on src/main/java/mx/com/sw/services/issue/BaseStampIssueJsonV4.java
> +    protected Map<String, String> getHeaders(String emails, String customId, boolean extra) throws ServicesException {
Se modifica para que sea más representativo a la función que tiene el parámetro.
Gracias

2024-01-08 21:38 UTC, SebastianSW approved these changes

2024-01-08 22:00 UTC, SwAeyrton commented on src/main/java/mx/com/sw/helpers/GeneralValidations.java
> +    protected boolean validateEmails(String emails) throws ServicesException {
Ah pues si ya existia el metodo recibiendo un string, se puede hacer que ese mismo metodo pueda recibir los emails como array, nada mas se cambia el tipo de dato con el mismo nombre del metodo. Porque tienes razon, si lo quitamos podriamos afectar a quien ya lo tiene integrado asi, no se que opines.

2024-01-08 22:15 UTC, FerCarrilloM commented on src/main/java/mx/com/sw/helpers/GeneralValidations.java
> +    protected boolean validateEmails(String emails) throws ServicesException {
Considere seguir tu consejo inicial y cambie el tipo de dato para que el cliente pueda enviar un array de strings.
Y así pueda enviar hasta 5, se validen y el código quede más corto para futuras tareas.
![image](https://github.com/lunasoft/sdk-java18/assets/108951984/39100bd2-ece7-4986-9aca-885acab06f04)

2024-01-09 18:15 UTC, marifersw approved these changes

2024-01-11 15:56 UTC, SwAeyrton approved these changes

2024-01-11 17:06 UTC, merged