Se corrige error ":org.apache.http.ContentTooLongException: Content length is too long"
lunasoft/sdk-java18 pull request #7
Opened 2021-03-16 18:01 UTC by DanielIxiguez

Se corrige error ":org.apache.http.ContentTooLongException: Content length is too long: " para solicitudes con body mayor a  25kB pasansdo de asíncrono a síncrono

2021-03-16 18:06 UTC, JuanGamezSW requested changes
Falta subir en el pom la versión

2021-03-16 18:06 UTC, JuanGamezSW commented on src/main/java/mx/com/sw/services/ResponseHandler.java
> +            //HttpResponse response = future.get(MAX_EXECUTION_TIME, TimeUnit.MINUTES);
Código comentado

2021-03-16 18:26 UTC, JuanGamezSW approved these changes

2021-03-16 23:05 UTC, RICH-CD approved these changes

2021-03-17 20:25 UTC, helttonrl approved these changes

2021-03-18 21:54 UTC, merged